=== megastacks13/SEW-MotoGP/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://uniovi.es/circuito" elementFormDefault="qualified" targetNamespace="http://uniovi.es/circuito" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="geografia" />
				<xs:element ref="dimensiones" />
				<xs:element ref="carrera" />
				<xs:element ref="resultados" />
				<xs:element ref="rankingMundial" />
				<xs:element ref="galerias" />
				<xs:element ref="plano" />
				<xs:element ref="bibliografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="geografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pais" />
				<xs:element ref="localidad" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pais" type="xs:string" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="dimensiones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
                <!-- Cambio de las unidades para tener un doble -->
				<xs:extension base="xs:double">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
                <!-- Cambio de las unidades para tener un doble -->
				<xs:extension base="xs:double">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="carrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="patrocinador" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    <!-- Cambio de las unidades para tener un date -->
	<xs:element name="fecha" type="xs:date" />
    <!-- Cambio de las unidades para tener un time -->
	<xs:element name="hora" type="xs:time" />
    <!-- Cambio de las unidades para tener un entero -->
	<xs:element name="vueltas" type="xs:int" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="resultados">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
                    <!-- Cambio de las unidades para tener un entero -->
					<xs:attribute default="0" name="puntos" type="xs:int" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
    <!-- Elimino el requisito de unidad al completo al usar duration -->
	<xs:element name="tiempo" type="xs:duration"/>
	<xs:element name="rankingMundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
				<xs:element ref="piloto" />
				<xs:element ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="galerias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="galeriafotos" />
				<xs:element ref="galeriavideos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriafotos">
		<xs:complexType>
			<xs:sequence>
                <!-- Añadimos el límite de ocurrencias -->
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:attribute name="src" type="xs:string" use="required" />
			<xs:attribute default="" name="alt" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriavideos">
		<xs:complexType>
			<xs:sequence>
                <!-- Añadimos el límite de ocurrencias -->
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:attribute name="src" type="xs:string" use="required" />
			<xs:attribute default="" name="alt" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="plano">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="punto" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
            <!-- Cambio de las unidades para tener un doble -->
			<xs:attribute name="longitud" type="xs:double" use="required" />
            <!-- Cambio de las unidades para tener un doble -->
			<xs:attribute name="latitud" type="xs:double" use="required" />
            <!-- Cambio de las unidades para tener un doble -->
			<xs:attribute name="altura" type="xs:double" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="punto" />
			</xs:sequence>
            <!-- Cambio de las unidades para tener un entero -->
			<xs:attribute name="numeroSector" type="xs:int" use="required" />
            <!-- Cambio de las unidades para tener un doble -->
			<xs:attribute name="distancia" type="xs:double" use="required" />
			<xs:attribute name="unidad" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="bibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="src" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>
</xs:schema>

=== megastacks13/SEW-MotoGP/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8" ?>

<circuito xmlns="http://uniovi.es/circuito"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://uniovi.es/circuito circuito.xsd">
    <nombre>Mobility Resort Motegi</nombre>

    <geografía>
        <pais>Japón</pais>
        <localidad>Motegi-machi</localidad>
    </geografía>

    <dimensiones>
        <longitud unidades="metros">4800</longitud>
        <anchura unidades="metros">10</anchura>
    </dimensiones>

    <carrera>
        <fecha>2025-09-28</fecha>
        <hora>07:00:00</hora>
        <vueltas>24</vueltas>
        <patrocinador>Motul</patrocinador>
    </carrera>
    
    <resultados>
        <piloto>Francesco Bagnaia</piloto>
        <tiempo>PT42M09.312S</tiempo>
    </resultados>
    
    <rankingMundial>
        <piloto puntos="541">Marc Marquez</piloto>
        <piloto puntos="340">Alex Marquez</piloto>
        <piloto puntos="274">Francesco Bagnaia</piloto>
    </rankingMundial>
    
    <galerias>
        <galeriafotos>
            <foto src="multimedia/img/motegi_skyview.jpg" alt="Foto desde el cielo de Motegi."/>
            <foto src="multimedia/img/motegi_carps.jpg" alt="Foto de carpas en el pit de Motegi."/>
            <foto src="multimedia/img/motegi_podium.jpg" alt="Foto del podium de Motegi."/>
            <foto src="multimedia/img/motegi_race.jpg" alt="Foto de Motegi en competición."/>
            <foto src="multimedia/img/motegi_entrance.jpg" alt="Foto de entrada en meta de un piloto haciendo un caballito."/>
        </galeriafotos>
        <galeriavideos>
            <video src="multimedia/video/Motegi Race Highlights.mp4"/>
            <video src="multimedia/video/First Turn Motegi 25.mp4"/>
            <video src="multimedia/video/Motegi Sprint Start.mp4"/>
        </galeriavideos>
    </galerias>
    
    <plano>
        <!-- Punto Inicial -->
        <punto longitud="140.2266254" latitud="36.5331544" altura="153.76"/>

        <!-- Tramos -->
        <tramos>
            <tramo distancia="246.42" numeroSector="1" unidad="metros">
                <punto longitud="140.2253702" latitud="36.5351305" altura="153.1"/>
            </tramo>
            <tramo distancia="51.97" numeroSector="2" unidad="metros">
                <punto longitud="140.2257488" latitud="36.5354854" altura="153.32"/>
            </tramo>
            <tramo distancia="55.78" numeroSector="3" unidad="metros">
                <punto longitud="140.2263676" latitud="36.5355433" altura="153.04"/>
            </tramo>
            <tramo distancia="567.15" numeroSector="4" unidad="metros">
                <punto longitud="140.2300680" latitud="36.5313955" altura="152.72"/>
            </tramo>
            <tramo distancia="35.58" numeroSector="5" unidad="metros">
                <punto longitud="140.2304633" latitud="36.5314282" altura="153.29"/>
            </tramo>
            <tramo distancia="98.78" numeroSector="6" unidad="metros">
                <punto longitud="140.2310973" latitud="36.5321566" altura="153.55"/>
            </tramo>
            <tramo distancia="59.35" numeroSector="7" unidad="metros">
                <punto longitud="140.2308445" latitud="36.5326510" altura="152.92"/>
            </tramo>
            <tramo distancia="515.42" numeroSector="8" unidad="metros">
                <punto longitud="140.2270096" latitud="36.5361145" altura="150.47"/>
            </tramo>
            <tramo distancia="36.17" numeroSector="9" unidad="metros">
                <punto longitud="140.2272730" latitud="36.5363616" altura="149.65"/>
            </tramo>
            <tramo distancia="239.87" numeroSector="10" unidad="metros">
                <punto longitud="140.2299473" latitud="36.5364852" altura="149.46"/>
            </tramo>
            <tramo distancia="77.03" numeroSector="11" unidad="metros">
                <punto longitud="140.2306558" latitud="36.5360915" altura="149.82"/>
            </tramo>
            <tramo distancia="272.37" numeroSector="12" unidad="metros">
                <punto longitud="140.2322311" latitud="36.5339919" altura="158.95"/>
            </tramo>
            <tramo distancia="34.32" numeroSector="13" unidad="metros">
                <punto longitud="140.2325895" latitud="36.5338825" altura="160.31"/>
            </tramo>
            <tramo distancia="66.9" numeroSector="14" unidad="metros">
                <punto longitud="140.2333110" latitud="36.5340389" altura="162.78"/>
            </tramo>
            <tramo distancia="55.18" numeroSector="15" unidad="metros">
                <punto longitud="140.2339270" latitud="36.5340280" altura="165.94"/>
            </tramo>
            <tramo distancia="53.1" numeroSector="16" unidad="metros">
                <punto longitud="140.2343220" latitud="36.5336711" altura="167.61"/>
            </tramo>
            <tramo distancia="240.19" numeroSector="17" unidad="metros">
                <punto longitud="140.2343138" latitud="36.5315066" altura="168.83"/>
            </tramo>
            <tramo distancia="41.05" numeroSector="18" unidad="metros">
                <punto longitud="140.2347526" latitud="36.5313996" altura="169.47"/>
            </tramo>
            <tramo distancia="395.29" numeroSector="19" unidad="metros">
                <punto longitud="140.2381555" latitud="36.5336683" altura="177.75"/>
            </tramo>
            <tramo distancia="26.68" numeroSector="20" unidad="metros">
                <punto longitud="140.2384208" latitud="36.5335589" altura="178.01"/>
            </tramo>
            <tramo distancia="32.01" numeroSector="21" unidad="metros">
                <punto longitud="140.2385699" latitud="36.5333500" altura="152.74"/>
            </tramo>
            <tramo distancia="779.59" numeroSector="22" unidad="metros">
                <punto longitud="140.2321691" latitud="36.5285886" altura="155.76"/>
            </tramo>
            <tramo distancia="152.74" numeroSector="23" unidad="metros">
                <punto longitud="140.2317592" latitud="36.5285384" altura="152.74"/>
            </tramo>
            <tramo distancia="213.67" numeroSector="24" unidad="metros">
                <punto longitud="140.2306018" latitud="36.5300994" altura="147.45"/>
            </tramo>
            <tramo distancia="117.84" numeroSector="25" unidad="metros">
                <punto longitud="140.2293284" latitud="36.5303672" altura="150.29"/>
            </tramo>
            <tramo distancia="52.45" numeroSector="26" unidad="metros">
                <punto longitud="140.2288407" latitud="36.5301055" altura="151.92"/>
            </tramo>
            <tramo distancia="392.2" numeroSector="27" unidad="metros">
                <punto longitud="140.2266254" latitud="36.5331544" altura="153.76"/>
            </tramo>
        </tramos>
    </plano>
    
    <bibliografía>
        <referencia>https://www.mr-motegi.jp/eng/motogp</referencia>
        <referencia>https://www.motogp.com/</referencia>
        <referencia>https://es.wikipedia.org/wiki/Mobility_Resort_Moteg</referencia>
    </bibliografía>

</circuito>
