=== megastacks13/SEW-MotoGP/xml/circuito.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT circuito (nombre, geografía, dimensiones, carrera, resultados, rankingMundial, galerias, plano, bibliografía)>

<!-- Especificaciones generales del circuito -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT geografía (pais, localidad)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>

<!--Dimensiones del circuito -->
<!ELEMENT dimensiones (longitud, anchura)>
<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura unidades CDATA #REQUIRED>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidades CDATA #REQUIRED>

<!-- Especificaciones de carrera -->
<!ELEMENT carrera (fecha, hora, vueltas, patrocinador)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!-- Resultados de carrera -->
<!ELEMENT resultados (piloto, tiempo)>
<!ELEMENT piloto (#PCDATA)>
<!ATTLIST piloto puntos (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ATTLIST tiempo unidad CDATA #REQUIRED>

<!-- Estado del mundial post-carrera -->
<!ELEMENT rankingMundial (piloto, piloto, piloto)>

<!ELEMENT galerias (galeriafotos, galeriavideos)>
<!-- Galería fotos -->
<!ELEMENT galeriafotos (foto+)>
<!ELEMENT foto (#PCDATA)>

<!-- Galería video -->
<!ELEMENT galeriavideos (video+)>
<!ELEMENT video (#PCDATA)>

<!-- Plano -->
<!ELEMENT plano (punto, tramos)>

<!-- Puntos (origen y final de tramo) -->
<!ELEMENT punto EMPTY>
<!ATTLIST punto longitud CDATA #REQUIRED>
<!ATTLIST punto latitud CDATA #REQUIRED>
<!ATTLIST punto altura CDATA #REQUIRED>

<!ELEMENT tramos (tramo+)>
<!-- Tramo -->
<!ELEMENT tramo (punto)>
<!ATTLIST tramo numeroSector CDATA #REQUIRED>
<!ATTLIST tramo distancia CDATA #REQUIRED>
<!ATTLIST tramo unidad CDATA #REQUIRED>


<!-- Referencias -->
<!ELEMENT bibliografía (referencia,referencia,referencia+)>
<!ELEMENT referencia (#PCDATA)>

=== megastacks13/SEW-MotoGP/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>Mobility Resort Motegi</nombre>

    <geografía>
        <pais>Japón</pais>
        <localidad>Motegi-machi</localidad>
    </geografía>

    <dimensiones>
        <longitud unidades="metros">4800</longitud>
        <anchura unidades="metros">10</anchura>
    </dimensiones>

    <carrera>
        <fecha>28-09-2025</fecha>
        <hora>07:00</hora>
        <vueltas>24</vueltas>
        <patrocinador>Motul</patrocinador>
    </carrera>
    
    <resultados>
        <piloto>Francesco Bagnaia</piloto>
        <tiempo unidad="mm:ss.0000">42:09.312</tiempo>
    </resultados>
    
    <rankingMundial>
        <piloto puntos="541">Marc Marquez</piloto>
        <piloto puntos="340">Alex Marquez</piloto>
        <piloto puntos="274">Francesco Bagnaia</piloto>
    </rankingMundial>
    
    <galerias>
        <galeriafotos>
            <foto></foto>
            <foto></foto>
            <foto></foto>
            <foto></foto>
            <foto></foto>
        </galeriafotos>
        <galeriavideos>
            <video></video>
            <video></video>
            <video></video>
        </galeriavideos>
    </galerias>
    
    <plano>
        <!-- Punto Inicial -->
        <punto longitud="" latitud="" altura=""/>

        <!-- Tramos -->
        <tramos>
            <tramo distancia="" numeroSector="" unidad="">
                <punto longitud="" latitud="" altura=""/>
            </tramo>
            <tramo distancia="" numeroSector="" unidad="">
                <punto longitud="" latitud="" altura=""/>
            </tramo>
            <tramo distancia="" numeroSector="" unidad="">
                <punto longitud="" latitud="" altura=""/>
            </tramo>
            <tramo distancia="" numeroSector="" unidad="">
                <punto longitud="" latitud="" altura=""/>
            </tramo>
        </tramos>
    </plano>
    
    <bibliografía>
        <referencia>https://www.mr-motegi.jp/eng/motogp</referencia>
        <referencia>https://www.motogp.com/</referencia>
        <referencia>https://es.wikipedia.org/wiki/Mobility_Resort_Moteg</referencia>
    </bibliografía>

</circuito>
